# https://github.com/google-github-actions/upload-cloud-storage
# https://github.com/google-github-actions/auth?tab=readme-ov-file#preferred-direct-workload-identity-federation
name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.14.0
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - uses: 'google-github-actions/auth@v2'
      with:
        project_id: 'dfar55'
        workload_identity_provider: 'projects/484405657577/locations/global/workloadIdentityPools/github/providers/my-repo'
    - uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: '/dist/budgeteer/browser'
        destination: 'b.dfar.io'
